name: flutter_inset_box_shadow
description: This package extends BoxShadow and BoxDecoration to support the inset property.
version: 1.0.8
repository: https://github.com/qoumo/flutter_inset_box_shadow

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
